version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.11-management
    ports:
      - 5670:5672
      - 15670:15672
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./docker_data/rabbitmq_single/:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: tester
      RABBITMQ_DEFAULT_PASS: tester
      RABBITMQ_LOGS:
      RABBITMQ_LOG_BASE: /var/log/rabbitmq
  amqproxy:
    container_name: amqproxy
    image: cloudamqp/amqproxy
    ports:
      - 5680:5673
    volumes:
      - ./docker_data/amqproxy/tmp:/tmp
    environment:
      LISTEN_ADDRESS: 0.0.0.0
      LISTEN_PORT: 5673
      AMQP_URL: amqp://rabbitmq:5672
      #AMQP_URL: amqp://192.168.1.106:5670
    #command: /app/bin/amqproxy
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 9988:9988
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/conf.d/:/etc/nginx/conf.d/ 
    #links:
    #  - amqproxy
    restart: always
